# ============================================================================
# TPT Doctor — Ansible Inventory
# ============================================================================
---
all:
  children:
    production:
      hosts:
        tpt-doctor-prod:
          ansible_host: 0.0.0.0
          ansible_user: root
          ansible_fqdn: doctor.tptpractice.com
          environment: production

    staging:
      hosts:
        tpt-doctor-staging:
          ansible_host: 0.0.0.0
          ansible_user: root
          ansible_fqdn: staging.tptpractice.com
          environment: staging

  vars:
    ansible_python_interpreter: /usr/bin/python3