// ============================================================================
// TPT Doctor — Shared Enums
// ============================================================================

export enum UserRole {
  SUPER_ADMIN = 'SUPER_ADMIN',
  PRACTICE_ADMIN = 'PRACTICE_ADMIN',
  DOCTOR = 'DOCTOR',
  NURSE = 'NURSE',
  RECEPTIONIST = 'RECEPTIONIST',
  PATIENT = 'PATIENT',
}

export enum Permission {
  // Patient management
  PATIENT_READ = 'PATIENT_READ',
  PATIENT_CREATE = 'PATIENT_CREATE',
  PATIENT_UPDATE = 'PATIENT_UPDATE',
  PATIENT_DELETE = 'PATIENT_DELETE',

  // EHR / Medical Records
  EHR_READ = 'EHR_READ',
  EHR_CREATE = 'EHR_CREATE',
  EHR_UPDATE = 'EHR_UPDATE',
  EHR_DELETE = 'EHR_DELETE',

  // Appointments
  APPOINTMENT_READ = 'APPOINTMENT_READ',
  APPOINTMENT_CREATE = 'APPOINTMENT_CREATE',
  APPOINTMENT_UPDATE = 'APPOINTMENT_UPDATE',
  APPOINTMENT_DELETE = 'APPOINTMENT_DELETE',

  // Billing
  BILLING_READ = 'BILLING_READ',
  BILLING_CREATE = 'BILLING_CREATE',
  BILLING_UPDATE = 'BILLING_UPDATE',
  BILLING_DELETE = 'BILLING_DELETE',

  // Prescriptions
  PRESCRIPTION_READ = 'PRESCRIPTION_READ',
  PRESCRIPTION_CREATE = 'PRESCRIPTION_CREATE',
  PRESCRIPTION_UPDATE = 'PRESCRIPTION_UPDATE',
  PRESCRIPTION_DELETE = 'PRESCRIPTION_DELETE',

  // Lab
  LAB_READ = 'LAB_READ',
  LAB_CREATE = 'LAB_CREATE',
  LAB_UPDATE = 'LAB_UPDATE',
  LAB_DELETE = 'LAB_DELETE',

  // Staff
  STAFF_READ = 'STAFF_READ',
  STAFF_CREATE = 'STAFF_CREATE',
  STAFF_UPDATE = 'STAFF_UPDATE',
  STAFF_DELETE = 'STAFF_DELETE',

  // Admin
  ADMIN_ACCESS = 'ADMIN_ACCESS',
  TENANT_MANAGE = 'TENANT_MANAGE',
  AUDIT_LOG_VIEW = 'AUDIT_LOG_VIEW',
  REPORT_VIEW = 'REPORT_VIEW',
  REPORT_CREATE = 'REPORT_CREATE',
}

export enum AppointmentStatus {
  SCHEDULED = 'SCHEDULED',
  CONFIRMED = 'CONFIRMED',
  CHECKED_IN = 'CHECKED_IN',
  IN_PROGRESS = 'IN_PROGRESS',
  COMPLETED = 'COMPLETED',
  CANCELLED = 'CANCELLED',
  NO_SHOW = 'NO_SHOW',
  RESCHEDULED = 'RESCHEDULED',
}

export enum EncounterType {
  OFFICE_VISIT = 'OFFICE_VISIT',
  TELEMEDICINE = 'TELEMEDICINE',
  HOME_VISIT = 'HOME_VISIT',
  EMERGENCY = 'EMERGENCY',
  FOLLOW_UP = 'FOLLOW_UP',
  ROUTINE_CHECKUP = 'ROUTINE_CHECKUP',
  CONSULTATION = 'CONSULTATION',
}

export enum Gender {
  MALE = 'MALE',
  FEMALE = 'FEMALE',
  NON_BINARY = 'NON_BINARY',
  OTHER = 'OTHER',
  PREFER_NOT_TO_SAY = 'PREFER_NOT_TO_SAY',
}

export enum BloodType {
  A_POSITIVE = 'A+',
  A_NEGATIVE = 'A-',
  B_POSITIVE = 'B+',
  B_NEGATIVE = 'B-',
  AB_POSITIVE = 'AB+',
  AB_NEGATIVE = 'AB-',
  O_POSITIVE = 'O+',
  O_NEGATIVE = 'O-',
  UNKNOWN = 'UNKNOWN',
}

export enum MaritalStatus {
  SINGLE = 'SINGLE',
  MARRIED = 'MARRIED',
  DIVORCED = 'DIVORCED',
  WIDOWED = 'WIDOWED',
  SEPARATED = 'SEPARATED',
  DOMESTIC_PARTNER = 'DOMESTIC_PARTNER',
}

export enum InsuranceType {
  PRIVATE = 'PRIVATE',
  MEDICARE = 'MEDICARE',
  MEDICAID = 'MEDICAID',
  VA = 'VA',
  SELF_PAY = 'SELF_PAY',
  WORKERS_COMP = 'WORKERS_COMP',
}

export enum ClaimStatus {
  DRAFT = 'DRAFT',
  SUBMITTED = 'SUBMITTED',
  ACCEPTED = 'ACCEPTED',
  REJECTED = 'REJECTED',
  PAID = 'PAID',
  DENIED = 'DENIED',
  APPEALED = 'APPEALED',
}

export enum PaymentStatus {
  PENDING = 'PENDING',
  COMPLETED = 'COMPLETED',
  FAILED = 'FAILED',
  REFUNDED = 'REFUNDED',
  PARTIALLY_REFUNDED = 'PARTIALLY_REFUNDED',
}

export enum PrescriptionStatus {
  DRAFT = 'DRAFT',
  SUBMITTED = 'SUBMITTED',
  FILLED = 'FILLED',
  PARTIALLY_FILLED = 'PARTIALLY_FILLED',
  CANCELLED = 'CANCELLED',
  EXPIRED = 'EXPIRED',
}

export enum LabStatus {
  ORDERED = 'ORDERED',
  SPECIMEN_COLLECTED = 'SPECIMEN_COLLECTED',
  IN_TRANSIT = 'IN_TRANSIT',
  IN_PROGRESS = 'IN_PROGRESS',
  COMPLETED = 'COMPLETED',
  REVIEWED = 'REVIEWED',
  CANCELLED = 'CANCELLED',
}

export enum AuditAction {
  CREATE = 'CREATE',
  READ = 'READ',
  UPDATE = 'UPDATE',
  DELETE = 'DELETE',
  LOGIN = 'LOGIN',
  LOGOUT = 'LOGOUT',
  EXPORT = 'EXPORT',
  PRINT = 'PRINT',
  VIEW_PHI = 'VIEW_PHI',
  CONSENT_GRANTED = 'CONSENT_GRANTED',
  CONSENT_REVOKED = 'CONSENT_REVOKED',
  DATA_BREACH = 'DATA_BREACH',
}

export enum ConsentType {
  TREATMENT = 'TREATMENT',
  PAYMENT = 'PAYMENT',
  HEALTHCARE_OPERATIONS = 'HEALTHCARE_OPERATIONS',
  RESEARCH = 'RESEARCH',
  MARKETING = 'MARKETING',
  DISCLOSURE = 'DISCLOSURE',
  TELEMEDICINE = 'TELEMEDICINE',
  RECORDING = 'RECORDING',
}

export enum ComplianceFramework {
  // US
  HIPAA = 'HIPAA',
  HIPAA_HITECH = 'HIPAA_HITECH',
  // Europe
  GDPR = 'GDPR',
  UK_GDPR = 'UK_GDPR',
  BDSG = 'BDSG',               // Germany
  AVG = 'AVG',                  // Netherlands
  LOI_INFORMATIQUE = 'LOI_INFORMATIQUE', // France
  PDL = 'PDL',                  // Sweden
  // Oceania
  AU_PRIVACY = 'AU_PRIVACY',
  NZ_HISO = 'NZ_HISO',
  // SE Asia
  SG_PDPA = 'SG_PDPA',          // Singapore
  MY_PDPA = 'MY_PDPA',          // Malaysia
  ID_PDP = 'ID_PDP',            // Indonesia
  TH_PDPA = 'TH_PDPA',          // Thailand
  PH_DPA = 'PH_DPA',            // Philippines
  // Canada
  PIPEDA = 'PIPEDA',
  // Switzerland
  CH_DSG = 'CH_DSG',
}

export enum DataRegion {
  US = 'US',
  EU = 'EU',
  AU = 'AU',
  NZ = 'NZ',
}

export enum Severity {
  INFO = 'INFO',
  WARNING = 'WARNING',
  ERROR = 'ERROR',
  CRITICAL = 'CRITICAL',
}

export enum NotificationType {
  APPOINTMENT_REMINDER = 'APPOINTMENT_REMINDER',
  LAB_RESULT = 'LAB_RESULT',
  MESSAGE = 'MESSAGE',
  PRESCRIPTION_REFILL = 'PRESCRIPTION_REFILL',
  BILLING = 'BILLING',
  SYSTEM = 'SYSTEM',
}

export enum WaitlistStatus {
  WAITING = 'WAITING',
  NOTIFIED = 'NOTIFIED',
  BOOKED = 'BOOKED',
  CANCELLED = 'CANCELLED',
  EXPIRED = 'EXPIRED',
}

export enum PTOStatus {
  PENDING = 'PENDING',
  APPROVED = 'APPROVED',
  DENIED = 'DENIED',
  CANCELLED = 'CANCELLED',
}

export enum CredentialStatus {
  ACTIVE = 'ACTIVE',
  EXPIRED = 'EXPIRED',
  PENDING_RENEWAL = 'PENDING_RENEWAL',
  REVOKED = 'REVOKED',
  SUSPENDED = 'SUSPENDED',
}

export enum CredentialType {
  MEDICAL_LICENSE = 'MEDICAL_LICENSE',
  BOARD_CERTIFICATION = 'BOARD_CERTIFICATION',
  DEA_REGISTRATION = 'DEA_REGISTRATION',
  NPI_NUMBER = 'NPI_NUMBER',
  MALPRACTICE_INSURANCE = 'MALPRACTICE_INSURANCE',
  BLS_CERTIFICATION = 'BLS_CERTIFICATION',
  ACLS_CERTIFICATION = 'ACLS_CERTIFICATION',
  CONTINUING_EDUCATION = 'CONTINUING_EDUCATION',
  HOSPITAL_PRIVILEGES = 'HOSPITAL_PRIVILEGES',
  MEDICAID_PROVIDER = 'MEDICAID_PROVIDER',
  MEDICARE_PROVIDER = 'MEDICARE_PROVIDER',
}

export enum CheckInStatus {
  PENDING = 'PENDING',
  CHECKED_IN = 'CHECKED_IN',
  CHECKED_OUT = 'CHECKED_OUT',
  NO_SHOW = 'NO_SHOW',
}

export enum ReminderChannel {
  EMAIL = 'EMAIL',
  SMS = 'SMS',
  BOTH = 'BOTH',
}

export enum ReminderStatus {
  PENDING = 'PENDING',
  SENT = 'SENT',
  FAILED = 'FAILED',
  CANCELLED = 'CANCELLED',
}

export enum DecisionSupportCategory {
  DRUG_INTERACTION = 'DRUG_INTERACTION',
  ALLERGY_CHECK = 'ALLERGY_CHECK',
  DOSAGE_CHECK = 'DOSAGE_CHECK',
  DUPLICATE_THERAPY = 'DUPLICATE_THERAPY',
  PREVENTIVE_CARE = 'PREVENTIVE_CARE',
  GUIDELINE_COMPLIANCE = 'GUIDELINE_COMPLIANCE',
  AGE_BASED = 'AGE_BASED',
  CONDITION_BASED = 'CONDITION_BASED',
}

export enum DecisionSupportSeverity {
  INFO = 'INFO',
  WARNING = 'WARNING',
  CRITICAL = 'CRITICAL',
}

// === Phase 3/4 Enums ===

export enum MessageTemplateCategory {
  APPOINTMENT_REMINDER = 'APPOINTMENT_REMINDER',
  LAB_RESULT = 'LAB_RESULT',
  PRESCRIPTION_REFILL = 'PRESCRIPTION_REFILL',
  BILLING = 'BILLING',
  GENERAL = 'GENERAL',
  WELCOME = 'WELCOME',
  FOLLOW_UP = 'FOLLOW_UP',
}

export enum WriteOffType {
  CHARITY = 'CHARITY',
  CONTRACTUAL = 'CONTRACTUAL',
  BAD_DEBT = 'BAD_DEBT',
  OTHER = 'OTHER',
}

export enum RefundStatus {
  PENDING = 'PENDING',
  PROCESSED = 'PROCESSED',
  FAILED = 'FAILED',
}

export enum StatementStatus {
  GENERATED = 'GENERATED',
  SENT = 'SENT',
  PAID = 'PAID',
  VOID = 'VOID',
}

export enum InsuranceVerificationStatus {
  VERIFIED = 'VERIFIED',
  PENDING = 'PENDING',
  FAILED = 'FAILED',
  EXPIRED = 'EXPIRED',
}

export enum ClaimSubmissionType {
  ORIGINAL = 'ORIGINAL',
  REPLACEMENT = 'REPLACEMENT',
  VOID = 'VOID',
}

export enum ClaimSubmissionStatus {
  PENDING = 'PENDING',
  SUBMITTED = 'SUBMITTED',
  ACCEPTED = 'ACCEPTED',
  REJECTED = 'REJECTED',
}

export enum EraStatus {
  RECEIVED = 'RECEIVED',
  APPLIED = 'APPLIED',
  DISPUTED = 'DISPUTED',
}

export enum ControlledSubstanceAction {
  PRESCRIBED = 'PRESCRIBED',
  DISPENSED = 'DISPENSED',
  ADMINISTERED = 'ADMINISTERED',
  WASTED = 'WASTED',
  RETURNED = 'RETURNED',
}

export enum EPrescribingTransactionType {
  NEW_SCRIPT = 'NEW_SCRIPT',
  REFILL = 'REFILL',
  CANCEL = 'CANCEL',
  RENEWAL = 'RENEWAL',
}

export enum EPrescribingStatus {
  PENDING = 'PENDING',
  SENT = 'SENT',
  DELIVERED = 'DELIVERED',
  ACKNOWLEDGED = 'ACKNOWLEDGED',
  ERROR = 'ERROR',
}

export enum LabIntegrationType {
  FHIR = 'FHIR',
  HL7 = 'HL7',
  CSV = 'CSV',
  API = 'API',
}

export enum CopayCollectionMethod {
  CASH = 'CASH',
  CARD = 'CARD',
  CHECK = 'CHECK',
  BILLED = 'BILLED',
}

export enum HsaFsaAccountType {
  HSA = 'HSA',
  FSA = 'FSA',
}

export enum CptCategory {
  EVALUATION_MGMT = 'EVALUATION_MGMT',
  SURGERY = 'SURGERY',
  RADIOLOGY = 'RADIOLOGY',
  LAB = 'LAB',
  MEDICINE = 'MEDICINE',
  ANESTHESIA = 'ANESTHESIA',
  OTHER = 'OTHER',
}

export enum BillingStatementSendMethod {
  EMAIL = 'EMAIL',
  MAIL = 'MAIL',
  PORTAL = 'PORTAL',
}

// === Phase 12: GP Practice Enhancement Enums ===

export enum ReferralStatus {
  DRAFT = 'DRAFT',
  SENT = 'SENT',
  ACKNOWLEDGED = 'ACKNOWLEDGED',
  BOOKED = 'BOOKED',
  COMPLETED = 'COMPLETED',
  CLOSED = 'CLOSED',
  CANCELLED = 'CANCELLED',
}

export enum ReferralPriority {
  URGENT = 'URGENT',
  SEMI_URGENT = 'SEMI_URGENT',
  ROUTINE = 'ROUTINE',
}

export enum ReferralType {
  EXTERNAL_SPECIALIST = 'EXTERNAL_SPECIALIST',
  INTERNAL_SPECIALIST = 'INTERNAL_SPECIALIST',
  ALLIED_HEALTH = 'ALLIED_HEALTH',
  DIAGNOSTIC_IMAGING = 'DIAGNOSTIC_IMAGING',
  PATHOLOGY = 'PATHOLOGY',
  HOSPITAL = 'HOSPITAL',
  COMMUNITY_SERVICE = 'COMMUNITY_SERVICE',
}

export enum CarePlanType {
  GP_MANAGEMENT_PLAN = 'GP_MANAGEMENT_PLAN',
  TEAM_CARE_ARRANGEMENT = 'TEAM_CARE_ARRANGEMENT',
  MENTAL_HEALTH_TREATMENT_PLAN = 'MENTAL_HEALTH_TREATMENT_PLAN',
  HEALTH_ASSESSMENT = 'HEALTH_ASSESSMENT',
  CHRONIC_DISEASE_MANAGEMENT = 'CHRONIC_DISEASE_MANAGEMENT',
  MULTIDISCIPLINARY_CARE = 'MULTIDISCIPLINARY_CARE',
}

export enum CarePlanStatus {
  ACTIVE = 'ACTIVE',
  COMPLETED = 'COMPLETED',
  CANCELLED = 'CANCELLED',
  EXPIRED = 'EXPIRED',
  REVIEW_DUE = 'REVIEW_DUE',
}

export enum CertificateType {
  SICK_LEAVE = 'SICK_LEAVE',
  WORKERS_COMPENSATION = 'WORKERS_COMPENSATION',
  FITNESS_FOR_WORK = 'FITNESS_FOR_WORK',
  MEDICAL_EXEMPTION = 'MEDICAL_EXEMPTION',
  VACCINATION_EXEMPTION = 'VACCINATION_EXEMPTION',
  ACC_INJURY_REPORT = 'ACC_INJURY_REPORT',
  WORKCOVER_CERTIFICATE = 'WORKCOVER_CERTIFICATE',
  GENERAL_MEDICAL = 'GENERAL_MEDICAL',
}

export enum CertificateStatus {
  DRAFT = 'DRAFT',
  ISSUED = 'ISSUED',
  VOID = 'VOID',
  EXPIRED = 'EXPIRED',
}

export enum IntakeStatus {
  PENDING = 'PENDING',
  COMPLETED = 'COMPLETED',
  REVIEWED = 'REVIEWED',
  REJECTED = 'REJECTED',
}

export enum CodingSystem {
  ICD10 = 'ICD10',
  ICD10_AM = 'ICD10_AM',
  SNOMED_CT = 'SNOMED_CT',
  LOINC = 'LOINC',
  CPT = 'CPT',
  READ_V2 = 'READ_V2',
}

export enum CountryCode {
  AU = 'AU',
  NZ = 'NZ',
  US = 'US',
  UK = 'UK',
  CA = 'CA',
  SG = 'SG',
  MY = 'MY',
  ID = 'ID',
  TH = 'TH',
  VN = 'VN',
  PH = 'PH',
  DE = 'DE',
  FR = 'FR',
  NL = 'NL',
  SE = 'SE',
  DK = 'DK',
  NO = 'NO',
  FI = 'FI',
  IE = 'IE',
  CH = 'CH',
  AT = 'AT',
  BE = 'BE',
}

export enum DiagnosisSystem {
  ICD10 = 'ICD10',
  ICD10_AM = 'ICD10_AM',
  SNOMED_CT = 'SNOMED_CT',
  READ_V2 = 'READ_V2',
  READ_V3 = 'READ_V3',
  SNOMED_CT_AU = 'SNOMED_CT_AU',
  SNOMED_CT_UK = 'SNOMED_CT_UK',
  SNOMED_CT_US = 'SNOMED_CT_US',
  SNOMED_CT_NZ = 'SNOMED_CT_NZ',
  SNOMED_CT_CA = 'SNOMED_CT_CA',
}

export enum MbsItemType {
  CONSULTATION = 'CONSULTATION',
  PROCEDURE = 'PROCEDURE',
  DIAGNOSTIC_IMAGING = 'DIAGNOSTIC_IMAGING',
  PATHOLOGY = 'PATHOLOGY',
  HEALTH_ASSESSMENT = 'HEALTH_ASSESSMENT',
  MENTAL_HEALTH = 'MENTAL_HEALTH',
  ALLIED_HEALTH = 'ALLIED_HEALTH',
  DENTAL = 'DENTAL',
  OTHER = 'OTHER',
}

export enum PbsCategory {
  GENERAL = 'GENERAL',
  CONCESSIONAL = 'CONCESSIONAL',
  SAFETY_NET = 'SAFETY_NET',
  REPATRIATION = 'REPATRIATION',
  OTHER = 'OTHER',
}

export enum MyHealthRecordDocumentType {
  SHARED_HEALTH_SUMMARY = 'SHARED_HEALTH_SUMMARY',
  EVENT_SUMMARY = 'EVENT_SUMMARY',
  DISCHARGE_SUMMARY = 'DISCHARGE_SUMMARY',
  REFERRAL = 'REFERRAL',
  PRESCRIPTION_RECORD = 'PRESCRIPTION_RECORD',
  DIAGNOSTIC_IMAGING_REPORT = 'DIAGNOSTIC_IMAGING_REPORT',
  PATHOLOGY_REPORT = 'PATHOLOGY_REPORT',
  SPECIALIST_LETTER = 'SPECIALIST_LETTER',
  ADVANCE_CARE_PLANNING = 'ADVANCE_CARE_PLANNING',
  MEDICARE_CLAIM = 'MEDICARE_CLAIM',
  IMMUNISATION_RECORD = 'IMMUNISATION_RECORD',
}

export enum NzClaimType {
  GP_VISIT = 'GP_VISIT',
  ACC_INJURY = 'ACC_INJURY',
  MATERNITY = 'MATERNITY',
  IMMUNISATION = 'IMMUNISATION',
  LABORATORY = 'LABORATORY',
  RADIOLOGY = 'RADIOLOGY',
  AFTER_HOURS = 'AFTER_HOURS',
  OTHER = 'OTHER',
}

export enum NhiStatus {
  ACTIVE = 'ACTIVE',
  DECEASED = 'DECEASED',
  EXPIRED = 'EXPIRED',
  CANCELLED = 'CANCELLED',
  NOT_FOUND = 'NOT_FOUND',
}

export enum UkClaimType {
  GMS = 'GMS',
  PMS = 'PMS',
  APMS = 'APMS',
  QOF = 'QOF',
  OTHER = 'OTHER',
}

export enum ProvincialHealthPlan {
  OHIP = 'OHIP',       // Ontario
  MSP = 'MSP',         // British Columbia
  RAMQ = 'RAMQ',       // Quebec
  AHCIP = 'AHCIP',     // Alberta
  SHCP = 'SHCP',       // Saskatchewan
  MB_COVERAGE = 'MB_COVERAGE', // Manitoba
  MSI = 'MSI',         // Nova Scotia
  NB_MEDICARE = 'NB_MEDICARE', // New Brunswick
  PEI_HC = 'PEI_HC',   // Prince Edward Island
  MCP = 'MCP',         // Newfoundland & Labrador
  YT_HC = 'YT_HC',     // Yukon
  NT_HC = 'NT_HC',     // Northwest Territories
  NU_HC = 'NU_HC',     // Nunavut
}

export enum ClaimSubmissionChannel {
  ELECTRONIC = 'ELECTRONIC',
  WEB_PORTAL = 'WEB_PORTAL',
  PAPER = 'PAPER',
  BATCH = 'BATCH',
}

export enum ClaimSubmissionMethod {
  MEDICARE_ONLINE = 'MEDICARE_ONLINE',
  ECLIPSE = 'ECLIPSE',
  HIB = 'HIB',
  FAX = 'FAX',
  PORTAL = 'PORTAL',
  EDI = 'EDI',
  GP_CONNECT = 'GP_CONNECT',
  SPINE = 'SPINE',
}

export enum AirVaccineStatus {
  RECORDED = 'RECORDED',
  PENDING = 'PENDING',
  ERROR = 'ERROR',
  DUPLICATE = 'DUPLICATE',
}

export enum NzImmunisationScheduleStatus {
  DUE = 'DUE',
  OVERDUE = 'OVERDUE',
  COMPLETED = 'COMPLETED',
  EXEMPT = 'EXEMPT',
  CONTRAINDICATED = 'CONTRAINDICATED',
  NOT_SCHEDULED = 'NOT_SCHEDULED',
}

export enum UkQofIndicatorStatus {
  ACHIEVED = 'ACHIEVED',
  NOT_ACHIEVED = 'NOT_ACHIEVED',
  EXCEPTION_REPORTED = 'EXCEPTION_REPORTED',
  NOT_APPLICABLE = 'NOT_APPLICABLE',
}

export enum CanadianDrugDbStatus {
  ACTIVE = 'ACTIVE',
  DISCONTINUED = 'DISCONTINUED',
  MARKETED = 'MARKETED',
  CANCELLED = 'CANCELLED',
}

export enum CountrySpecificPermission {
  // AU specific
  AU_MBS_CLAIM_SUBMIT = 'AU_MBS_CLAIM_SUBMIT',
  AU_PBS_PRESCRIBE = 'AU_PBS_PRESCRIBE',
  AU_MY_HEALTH_RECORD_ACCESS = 'AU_MY_HEALTH_RECORD_ACCESS',
  AU_AIR_SUBMIT = 'AU_AIR_SUBMIT',
  AU_PIP_REPORT_VIEW = 'AU_PIP_REPORT_VIEW',
  AU_GPMP_MANAGE = 'AU_GPMP_MANAGE',
  AU_TCA_MANAGE = 'AU_TCA_MANAGE',
  AU_MHTP_MANAGE = 'AU_MHTP_MANAGE',
  AU_HEALTH_ASSESSMENT_MANAGE = 'AU_HEALTH_ASSESSMENT_MANAGE',

  // NZ specific
  NZ_MOH_CLAIM_SUBMIT = 'NZ_MOH_CLAIM_SUBMIT',
  NZ_PHO_REPORT_VIEW = 'NZ_PHO_REPORT_VIEW',
  NZ_IMMUNISATION_SUBMIT = 'NZ_IMMUNISATION_SUBMIT',
  NZ_NHI_VALIDATE = 'NZ_NHI_VALIDATE',
  NZ_COMMUNITY_PHARMACY = 'NZ_COMMUNITY_PHARMACY',

  // UK specific
  UK_NHS_GP2GP = 'UK_NHS_GP2GP',
  UK_QOF_REPORT_VIEW = 'UK_QOF_REPORT_VIEW',
  UK_GP_CONNECT_ACCESS = 'UK_GP_CONNECT_ACCESS',
  UK_SPINE_ACCESS = 'UK_SPINE_ACCESS',
  UK_EPS_PRESCRIBE = 'UK_EPS_PRESCRIBE',

  // CA specific
  CA_PROVINCIAL_CLAIM_SUBMIT = 'CA_PROVINCIAL_CLAIM_SUBMIT',
  CA_INFOWAY_ACCESS = 'CA_INFOWAY_ACCESS',
  CA_DRUG_DB_LOOKUP = 'CA_DRUG_DB_LOOKUP',
  CA_IMMUNISATION_SUBMIT = 'CA_IMMUNISATION_SUBMIT',
}

export enum InboundReferralSource {
  GP = 'GP',
  SPECIALIST = 'SPECIALIST',
  HOSPITAL = 'HOSPITAL',
  ALLIED_HEALTH = 'ALLIED_HEALTH',
  PATIENT_SELF = 'PATIENT_SELF',
  OTHER = 'OTHER',
}
